import Link from 'next/link';

import { InvoraMark } from '@/components/brand/invora-mark';
import { LandingNavbar } from '@/components/marketing/landing-navbar';
import { buttonClassName } from '@/components/ui/button';
import { Icon, type IconName } from '@/components/ui/icon';
import {
  APP_NAME,
  APP_TAGLINE,
  MAIN_CONTENT_ELEMENT_ID,
  ROUTES,
} from '@/lib/constants';
import { cn } from '@/lib/utils';

interface MarketingItem {
  readonly title: string;
  readonly description: string;
  readonly icon: IconName;
}

const VALUE_PROPOSITIONS: readonly MarketingItem[] = [
  {
    title: 'Forecast with context',
    description: 'Turn historical sales into planning signals for the demand ahead.',
    icon: 'forecast',
  },
  {
    title: 'Keep stock under control',
    description: 'Review inventory state and bring low-stock risk into focus.',
    icon: 'inventory',
  },
  {
    title: 'Replenish intelligently',
    description: 'Use forecast and inventory context to review reorder decisions.',
    icon: 'recommendations',
  },
] as const;

const WORKFLOW: readonly MarketingItem[] = [
  {
    title: 'Organize products',
    description: 'Maintain the catalog your planning workflow depends on.',
    icon: 'products',
  },
  {
    title: 'Connect operations',
    description: 'Bring inventory state and historical sales into view.',
    icon: 'sales',
  },
  {
    title: 'Run a forecast',
    description: 'Create a demand forecast for a selected planning horizon.',
    icon: 'forecast',
  },
  {
    title: 'Review results',
    description: 'Inspect persisted predictions and available performance metrics.',
    icon: 'results',
  },
  {
    title: 'Plan replenishment',
    description: 'Review backend-generated reorder recommendations in context.',
    icon: 'recommendations',
  },
  {
    title: 'Stay informed',
    description: 'Use the dashboard and reports to guide operational conversations.',
    icon: 'reports',
  },
] as const;

const CAPABILITIES: readonly MarketingItem[] = [
  {
    title: 'Demand forecasting',
    description:
      'Create planning runs from sales history and review persisted forecast output.',
    icon: 'forecast',
  },
  {
    title: 'Inventory visibility',
    description: 'Monitor stock status, low-stock risk, and movement history.',
    icon: 'inventory',
  },
  {
    title: 'Reorder recommendations',
    description:
      'Surface replenishment decisions generated from forecast and inventory context.',
    icon: 'recommendations',
  },
  {
    title: 'Sales intelligence',
    description: 'Upload historical demand and explore transaction trends over time.',
    icon: 'sales',
  },
  {
    title: 'Forecast performance',
    description: 'Review prediction output and available metrics for completed runs.',
    icon: 'results',
  },
  {
    title: 'Business reports',
    description: 'Explore operational report views and export supported CSV reports.',
    icon: 'reports',
  },
  {
    title: 'Connected dashboard',
    description: 'See inventory, demand, and reorder signals in one overview.',
    icon: 'dashboard',
  },
  {
    title: 'Planning defaults',
    description:
      'Configure the forecast and inventory defaults represented in your workspace.',
    icon: 'settings',
  },
] as const;

const FAQS = [
  {
    question: 'What is Invora?',
    answer:
      'Invora is an inventory planning application that brings products, inventory, sales history, demand forecasts, and reorder recommendations into one workflow.',
  },
  {
    question: 'What data does Invora use for forecasting?',
    answer:
      'Forecast runs use the sales history available in the workspace. The resulting predictions and available metrics are persisted for review in Forecast Results.',
  },
  {
    question: 'Does uploading sales automatically change inventory?',
    answer:
      'No. Sales upload and Inventory are separate operational workflows. Inventory changes are recorded through its stock-movement controls.',
  },
  {
    question: 'How are reorder recommendations created?',
    answer:
      'Recommendations are generated by the backend from completed forecast output and inventory context. Invora presents those decisions for review; it does not create purchase orders from the browser.',
  },
  {
    question: 'Can forecast results be reviewed before recommendations?',
    answer:
      'Yes. Completed forecast runs link to persisted Forecast Results, where predictions and available metrics can be reviewed before moving into replenishment planning.',
  },
  {
    question: 'Can reports be exported?',
    answer: 'Supported report views can be exported as CSV from the Reports workspace.',
  },
] as const;

function SectionHeading({
  eyebrow,
  title,
  description,
  align = 'left',
}: {
  eyebrow: string;
  title: string;
  description: string;
  align?: 'left' | 'center';
}) {
  return (
    <div className={cn('max-w-2xl', align === 'center' && 'mx-auto text-center')}>
      <p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">
        {eyebrow}
      </p>
      <h2 className="mt-3 text-3xl font-semibold tracking-tight text-foreground sm:text-4xl">
        {title}
      </h2>
      <p className="mt-4 text-base leading-7 text-foreground-muted">{description}</p>
    </div>
  );
}

function PreviewMetric({
  label,
  value,
  tone,
}: {
  label: string;
  value: string;
  tone: 'primary' | 'success' | 'warning';
}) {
  const toneClass = {
    primary: 'bg-primary/10 text-primary',
    success: 'bg-success/10 text-success',
    warning: 'bg-warning/15 text-warning',
  }[tone];

  return (
    <div className="rounded-xl border border-border bg-background px-3 py-3">
      <p className="text-xs text-foreground-muted">{label}</p>
      <p className={cn('mt-1 text-sm font-semibold', toneClass)}>{value}</p>
    </div>
  );
}

function PreviewRow({
  label,
  status,
  tone,
}: {
  label: string;
  status: string;
  tone: 'primary' | 'success' | 'warning';
}) {
  const toneClass = {
    primary: 'bg-primary',
    success: 'bg-success',
    warning: 'bg-warning',
  }[tone];

  return (
    <div className="flex items-center justify-between gap-2 rounded-lg border border-border px-3 py-2.5">
      <span className="min-w-0 truncate text-xs font-medium text-foreground">
        {label}
      </span>
      <span className="inline-flex shrink-0 items-center gap-1.5 text-[0.68rem] font-medium text-foreground-muted">
        <span className={cn('size-1.5 rounded-full', toneClass)} />
        {status}
      </span>
    </div>
  );
}

function MarketingPreview() {
  return (
    <figure
      aria-label="Illustrative Invora planning workspace"
      className="relative overflow-hidden rounded-2xl border border-border bg-surface p-3 shadow-2xl shadow-primary/10 sm:p-5"
    >
      <div className="mb-4 flex items-center justify-between border-b border-border pb-3">
        <div className="flex items-center gap-2">
          <span className="size-2 rounded-full bg-danger" />
          <span className="size-2 rounded-full bg-warning" />
          <span className="size-2 rounded-full bg-success" />
          <span className="ml-2 hidden text-xs font-medium text-foreground-muted sm:block">
            Planning workspace
          </span>
        </div>
        <span className="rounded-full bg-primary/10 px-2.5 py-1 text-[0.68rem] font-semibold text-primary">
          Illustrative preview
        </span>
      </div>

      <div className="grid gap-3 sm:grid-cols-3">
        <PreviewMetric label="Demand view" value="Forecast ready" tone="primary" />
        <PreviewMetric label="Inventory risk" value="Needs review" tone="warning" />
        <PreviewMetric label="Replenishment" value="Actionable" tone="success" />
      </div>

      <div className="mt-4 grid gap-4 lg:grid-cols-[1.45fr_0.9fr]">
        <div className="rounded-xl border border-border bg-background p-4">
          <div className="flex items-start justify-between gap-3">
            <div>
              <p className="text-sm font-semibold text-foreground">Demand outlook</p>
              <p className="mt-1 text-xs text-foreground-muted">
                Historical demand and forecast horizon
              </p>
            </div>
            <span className="rounded-md bg-surface-muted px-2 py-1 text-[0.68rem] font-medium text-foreground-muted">
              30-day view
            </span>
          </div>
          <svg
            viewBox="0 0 480 180"
            role="img"
            aria-label="Illustrative historical and forecast demand chart"
            className="mt-4 h-40 w-full"
          >
            <path
              d="M24 20V152H456"
              stroke="currentColor"
              strokeWidth="1"
              className="text-border"
            />
            <path
              d="M28 128 C74 116 88 132 124 102 S176 110 205 78 S262 85 290 62"
              fill="none"
              stroke="currentColor"
              strokeWidth="5"
              strokeLinecap="round"
              className="text-primary"
            />
            <path
              d="M290 62 C326 48 348 74 378 50 S423 57 452 34"
              fill="none"
              stroke="currentColor"
              strokeWidth="5"
              strokeLinecap="round"
              strokeDasharray="9 8"
              className="text-accent"
            />
            <path
              d="M290 28V152"
              stroke="currentColor"
              strokeDasharray="4 5"
              className="text-border"
            />
            <text x="299" y="26" className="fill-foreground-muted text-[11px]">
              Forecast
            </text>
          </svg>
          <div className="flex items-center gap-4 text-xs text-foreground-muted">
            <span className="inline-flex items-center gap-1.5">
              <span className="size-2 rounded-full bg-primary" />
              Historical demand
            </span>
            <span className="inline-flex items-center gap-1.5">
              <span className="size-2 rounded-full bg-accent" />
              Projected demand
            </span>
          </div>
        </div>

        <div className="rounded-xl border border-border bg-background p-4">
          <div className="flex items-center justify-between gap-3">
            <div>
              <p className="text-sm font-semibold text-foreground">Reorder review</p>
              <p className="mt-1 text-xs text-foreground-muted">
                Illustrative decision list
              </p>
            </div>
            <Icon name="recommendations" className="text-primary" />
          </div>
          <div className="mt-4 space-y-3">
            <PreviewRow label="Essential item" status="Review stock" tone="warning" />
            <PreviewRow label="Steady seller" status="On track" tone="success" />
            <PreviewRow
              label="Planned demand"
              status="Forecast linked"
              tone="primary"
            />
          </div>
        </div>
      </div>
      <figcaption className="mt-3 px-1 text-xs text-foreground-muted">
        Static product illustration. It does not represent live customer data.
      </figcaption>
    </figure>
  );
}

function StockBar({
  label,
  value,
  width,
  tone,
}: {
  label: string;
  value: string;
  width: string;
  tone: string;
}) {
  return (
    <div>
      <div className="mb-2 flex items-center justify-between gap-3 text-sm">
        <span className="font-medium text-foreground">{label}</span>
        <span className="text-foreground-muted">{value}</span>
      </div>
      <div className="h-2 overflow-hidden rounded-full bg-surface-muted">
        <div className={cn('h-full rounded-full', width, tone)} />
      </div>
    </div>
  );
}

function ReorderTableRow({
  product,
  risk,
  action,
  tone,
}: {
  product: string;
  risk: string;
  action: string;
  tone: 'primary' | 'success' | 'warning';
}) {
  const toneClass = {
    primary: 'bg-primary/10 text-primary',
    success: 'bg-success/10 text-success',
    warning: 'bg-warning/15 text-warning',
  }[tone];

  return (
    <div className="grid grid-cols-[1.3fr_0.8fr_0.8fr] gap-2 px-4 py-4 text-sm">
      <span className="font-medium text-foreground">{product}</span>
      <span>
        <span className={cn('rounded-full px-2 py-1 text-xs font-semibold', toneClass)}>
          {risk}
        </span>
      </span>
      <span className="text-foreground-muted">{action}</span>
    </div>
  );
}

function Benefit({
  icon,
  title,
  text,
}: {
  icon: IconName;
  title: string;
  text: string;
}) {
  return (
    <article className="rounded-2xl border border-border bg-surface p-6 text-center shadow-sm">
      <span className="mx-auto flex size-11 items-center justify-center rounded-xl bg-primary/10 text-primary">
        <Icon name={icon} />
      </span>
      <h3 className="mt-5 text-lg font-semibold text-foreground">{title}</h3>
      <p className="mt-2 text-sm leading-6 text-foreground-muted">{text}</p>
    </article>
  );
}

function FooterLinks({
  title,
  links,
}: {
  title: string;
  links: readonly { readonly href: string; readonly label: string }[];
}) {
  return (
    <div>
      <h2 className="text-sm font-semibold text-foreground">{title}</h2>
      <ul className="mt-4 space-y-2.5">
        {links.map((link) => (
          <li key={link.href}>
            <Link
              href={link.href}
              className="text-sm text-foreground-muted transition-colors hover:text-foreground"
            >
              {link.label}
            </Link>
          </li>
        ))}
      </ul>
    </div>
  );
}

/** Public, API-independent product website for the Invora application. */
export function LandingPage() {
  const year = new Date().getFullYear();

  return (
    <div className="min-h-dvh overflow-x-hidden bg-background text-foreground">
      <a
        href={`#${MAIN_CONTENT_ELEMENT_ID}`}
        className="sr-only focus:not-sr-only focus:absolute focus:left-4 focus:top-4 focus:z-50 focus:rounded-md focus:bg-primary focus:px-4 focus:py-2 focus:text-sm focus:font-medium focus:text-primary-foreground"
      >
        Skip to main content
      </a>
      <LandingNavbar />
      <main id={MAIN_CONTENT_ELEMENT_ID} tabIndex={-1}>
        <section className="relative isolate overflow-hidden">
          <div
            aria-hidden="true"
            className="absolute inset-0 -z-10 bg-gradient-to-br from-primary/10 via-background to-accent/10"
          />
          <div
            aria-hidden="true"
            className="absolute inset-x-0 top-0 -z-10 h-full opacity-50 [background-image:linear-gradient(to_right,var(--color-border)_1px,transparent_1px),linear-gradient(to_bottom,var(--color-border)_1px,transparent_1px)] [background-size:4rem_4rem] [mask-image:linear-gradient(to_bottom,black,transparent_75%)]"
          />
          <div className="mx-auto grid max-w-7xl gap-12 px-4 py-20 sm:px-6 sm:py-24 lg:grid-cols-[0.9fr_1.1fr] lg:items-center lg:gap-14 lg:px-8 lg:py-28">
            <div className="max-w-2xl">
              <p className="inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/8 px-3 py-1.5 text-xs font-semibold tracking-wide text-primary">
                <Icon name="sparkles" className="size-3.5" />
                AI-powered inventory intelligence
              </p>
              <h1 className="mt-6 text-4xl font-semibold tracking-tight text-foreground sm:text-5xl lg:text-6xl">
                Predict demand. Protect inventory. Replenish with confidence.
              </h1>
              <p className="mt-6 max-w-xl text-lg leading-8 text-foreground-muted">
                Invora brings sales history, inventory state, forecasting, and reorder
                decisions into one focused planning workflow for inventory teams.
              </p>
              <div className="mt-8 flex flex-col gap-3 sm:flex-row">
                <Link
                  href={ROUTES.register}
                  className={buttonClassName({ size: 'lg' })}
                >
                  Get started <Icon name="arrow-right" className="size-4" />
                </Link>
                <a
                  href="#how-it-works"
                  className={buttonClassName({ variant: 'secondary', size: 'lg' })}
                >
                  Explore how it works
                </a>
              </div>
              <div className="mt-8 flex flex-wrap gap-x-6 gap-y-2 text-sm text-foreground-muted">
                <span className="inline-flex items-center gap-2">
                  <Icon name="check" className="size-4 text-success" />
                  Products and inventory context
                </span>
                <span className="inline-flex items-center gap-2">
                  <Icon name="check" className="size-4 text-success" />
                  Forecasts and recommendations
                </span>
              </div>
            </div>
            <MarketingPreview />
          </div>
        </section>

        <section
          id="product"
          className="border-y border-border bg-surface-muted/50 py-20 sm:py-24"
        >
          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <SectionHeading
              eyebrow="Inventory planning, connected"
              title="Move from fragmented operational data to a clearer next decision."
              description="Invora is designed around the everyday relationship between demand, stock position, forecasting, and replenishment review."
              align="center"
            />
            <div className="mt-12 grid gap-5 md:grid-cols-3">
              {VALUE_PROPOSITIONS.map((item) => (
                <article
                  key={item.title}
                  className="rounded-2xl border border-border bg-surface p-6 shadow-sm"
                >
                  <span className="flex size-11 items-center justify-center rounded-xl bg-primary/10 text-primary">
                    <Icon name={item.icon} />
                  </span>
                  <h3 className="mt-5 text-lg font-semibold text-foreground">
                    {item.title}
                  </h3>
                  <p className="mt-2 text-sm leading-6 text-foreground-muted">
                    {item.description}
                  </p>
                </article>
              ))}
            </div>
          </div>
        </section>

        <section id="how-it-works" className="py-20 sm:py-28">
          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <SectionHeading
              eyebrow="One connected workflow"
              title="From product records to replenishment planning."
              description="Each step builds on the operational context before it, so planning conversations have a clear path from inputs to action."
              align="center"
            />
            <ol className="relative mt-14 grid gap-6 md:grid-cols-2 xl:grid-cols-3">
              {WORKFLOW.map((step, index) => (
                <li
                  key={step.title}
                  className="relative rounded-2xl border border-border bg-surface p-6"
                >
                  <span className="absolute right-5 top-5 text-xs font-semibold tabular-nums text-foreground-muted">
                    0{index + 1}
                  </span>
                  <span className="flex size-11 items-center justify-center rounded-xl bg-accent/10 text-accent">
                    <Icon name={step.icon} />
                  </span>
                  <h3 className="mt-5 text-lg font-semibold text-foreground">
                    {step.title}
                  </h3>
                  <p className="mt-2 text-sm leading-6 text-foreground-muted">
                    {step.description}
                  </p>
                </li>
              ))}
            </ol>
          </div>
        </section>

        <section id="capabilities" className="bg-surface-muted/50 py-20 sm:py-28">
          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <SectionHeading
              eyebrow="Core capabilities"
              title="A practical toolkit for inventory intelligence."
              description="Each workspace is focused on an existing part of the Invora workflow—no detached analytics layer or invented product surface."
            />
            <div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
              {CAPABILITIES.map((item) => (
                <article
                  key={item.title}
                  className="group rounded-xl border border-border bg-surface p-5 transition-transform motion-safe:hover:-translate-y-1"
                >
                  <Icon name={item.icon} className="text-primary" />
                  <h3 className="mt-5 font-semibold text-foreground">{item.title}</h3>
                  <p className="mt-2 text-sm leading-6 text-foreground-muted">
                    {item.description}
                  </p>
                </article>
              ))}
            </div>
          </div>
        </section>

        <section id="insights" className="py-20 sm:py-28">
          <div className="mx-auto max-w-7xl space-y-20 px-4 sm:px-6 lg:space-y-28 lg:px-8">
            <div className="grid gap-10 lg:grid-cols-2 lg:items-center lg:gap-16">
              <SectionHeading
                eyebrow="Inventory intelligence"
                title="Look beyond a quantity on hand."
                description="Invora brings stock status and low-stock context alongside the planning signals that matter when replenishment is being reviewed."
              />
              <div className="rounded-2xl border border-border bg-surface p-5 shadow-sm sm:p-7">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="font-semibold text-foreground">Inventory attention</p>
                    <p className="mt-1 text-sm text-foreground-muted">
                      Illustrative stock context
                    </p>
                  </div>
                  <Icon name="inventory" className="text-accent" />
                </div>
                <div className="mt-7 space-y-4">
                  <StockBar
                    label="Healthy stock"
                    value="Available"
                    width="w-[82%]"
                    tone="bg-success"
                  />
                  <StockBar
                    label="Low-stock review"
                    value="Monitor"
                    width="w-[48%]"
                    tone="bg-warning"
                  />
                  <StockBar
                    label="Critical attention"
                    value="Plan action"
                    width="w-[24%]"
                    tone="bg-danger"
                  />
                </div>
                <div className="mt-7 rounded-xl border border-primary/20 bg-primary/6 p-4">
                  <p className="text-xs font-semibold uppercase tracking-wide text-primary">
                    Replenishment context
                  </p>
                  <p className="mt-1 text-sm text-foreground">
                    Review inventory state alongside forecast-informed recommendations.
                  </p>
                </div>
              </div>
            </div>

            <div className="grid gap-10 lg:grid-cols-2 lg:items-center lg:gap-16">
              <div className="order-2 rounded-2xl border border-border bg-surface p-5 shadow-sm sm:p-7 lg:order-1">
                <div className="flex items-start justify-between gap-3">
                  <div>
                    <p className="font-semibold text-foreground">Forecast review</p>
                    <p className="mt-1 text-sm text-foreground-muted">
                      Historical demand and projected planning window
                    </p>
                  </div>
                  <Icon name="forecast" className="text-primary" />
                </div>
                <svg
                  viewBox="0 0 560 190"
                  role="img"
                  aria-label="Illustrative forecasting chart"
                  className="mt-6 h-44 w-full"
                >
                  <path
                    d="M22 165H538M22 18v147"
                    stroke="currentColor"
                    className="text-border"
                  />
                  <path
                    d="M28 132 C76 124 88 86 128 106 S186 82 220 102 S274 68 316 86"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="5"
                    strokeLinecap="round"
                    className="text-primary"
                  />
                  <path
                    d="M316 86 C356 102 378 48 418 70 S470 44 532 38"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="5"
                    strokeLinecap="round"
                    strokeDasharray="10 8"
                    className="text-accent"
                  />
                  <path
                    d="M316 24V165"
                    stroke="currentColor"
                    strokeDasharray="4 5"
                    className="text-border"
                  />
                </svg>
                <div className="mt-2 grid grid-cols-2 gap-3 border-t border-border pt-5 text-sm">
                  <span className="text-foreground-muted">Historical demand</span>
                  <span className="text-right font-medium text-foreground">
                    Forecast horizon
                  </span>
                </div>
              </div>
              <div className="order-1 lg:order-2">
                <SectionHeading
                  eyebrow="Forecasting workflow"
                  title="Forecast demand, then review the result before acting."
                  description="Forecast Runs supports the planning lifecycle, while Forecast Results keeps persisted prediction output and available metrics ready for review."
                />
              </div>
            </div>

            <div className="grid gap-10 lg:grid-cols-2 lg:items-center lg:gap-16">
              <SectionHeading
                eyebrow="Replenishment planning"
                title="Turn operational context into a focused replenishment review."
                description="Recommendations surface backend-generated risk and reorder decisions so teams can make the next inventory conversation more deliberate."
              />
              <div className="overflow-hidden rounded-2xl border border-border bg-surface shadow-sm">
                <div className="grid grid-cols-[1.3fr_0.8fr_0.8fr] gap-2 border-b border-border bg-surface-muted px-4 py-3 text-[0.68rem] font-semibold uppercase tracking-wide text-foreground-muted">
                  <span>Planning item</span>
                  <span>Risk</span>
                  <span>Action</span>
                </div>
                <div className="divide-y divide-border">
                  <ReorderTableRow
                    product="Inventory item"
                    risk="Review"
                    action="Inspect"
                    tone="warning"
                  />
                  <ReorderTableRow
                    product="Forecast-linked item"
                    risk="Plan"
                    action="Review"
                    tone="primary"
                  />
                  <ReorderTableRow
                    product="Steady demand item"
                    risk="Stable"
                    action="Monitor"
                    tone="success"
                  />
                </div>
                <p className="px-4 py-3 text-xs text-foreground-muted">
                  Illustrative review state. Reorder quantities and risk remain
                  backend-generated in the application.
                </p>
              </div>
            </div>
          </div>
        </section>

        <section className="bg-surface-muted/50 py-20 sm:py-28">
          <div className="mx-auto grid max-w-7xl gap-10 px-4 sm:px-6 lg:grid-cols-[0.85fr_1.15fr] lg:items-center lg:px-8">
            <SectionHeading
              eyebrow="Business visibility"
              title="A single place to see operational signals and report on them."
              description="The dashboard presents key inventory, demand, and reorder context, while report views make structured operational data ready for review or supported CSV export."
            />
            <div className="grid gap-4 sm:grid-cols-2">
              <article className="rounded-2xl border border-border bg-surface p-6 shadow-sm">
                <Icon name="dashboard" className="text-primary" />
                <h3 className="mt-5 text-lg font-semibold text-foreground">
                  Dashboard signals
                </h3>
                <p className="mt-2 text-sm leading-6 text-foreground-muted">
                  Bring KPIs, demand trends, inventory risk, and reorder alerts into a
                  clear operational overview.
                </p>
              </article>
              <article className="rounded-2xl border border-border bg-surface p-6 shadow-sm sm:mt-8">
                <Icon name="reports" className="text-accent" />
                <h3 className="mt-5 text-lg font-semibold text-foreground">
                  Structured reports
                </h3>
                <p className="mt-2 text-sm leading-6 text-foreground-muted">
                  Review backend-defined report views and export supported data when a
                  spreadsheet handoff is useful.
                </p>
              </article>
            </div>
          </div>
        </section>

        <section className="py-20 sm:py-28">
          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <SectionHeading
              eyebrow="Why Invora"
              title="Planning clarity without disconnected workflow steps."
              description="Invora keeps the product focused on the decisions inventory teams need to review—not ornamental dashboards or browser-side calculations."
              align="center"
            />
            <div className="mt-12 grid gap-4 md:grid-cols-3">
              <Benefit
                icon="chart"
                title="Better visibility"
                text="Review demand, stock context, and planning output through connected application workspaces."
              />
              <Benefit
                icon="sparkles"
                title="Faster decisions"
                text="Move from historical demand to a forecast and a replenishment review without losing context."
              />
              <Benefit
                icon="shield"
                title="Clear responsibilities"
                text="Protected application routes present backend-owned calculations and user-scoped operational data."
              />
            </div>
          </div>
        </section>

        <section className="border-y border-border bg-surface-muted/50 py-16 sm:py-20">
          <div className="mx-auto flex max-w-4xl flex-col items-center gap-5 px-4 text-center sm:px-6">
            <span className="flex size-12 items-center justify-center rounded-2xl bg-success/10 text-success">
              <Icon name="shield" />
            </span>
            <div>
              <h2 className="text-2xl font-semibold tracking-tight text-foreground">
                Built for a protected operational workspace.
              </h2>
              <p className="mx-auto mt-3 max-w-2xl text-sm leading-6 text-foreground-muted">
                Invora uses authenticated access for business routes, keeps browser
                access tokens in memory, and relies on backend authorization for data
                and decision integrity.
              </p>
            </div>
          </div>
        </section>

        <section id="faq" className="py-20 sm:py-28">
          <div className="mx-auto grid max-w-7xl gap-12 px-4 sm:px-6 lg:grid-cols-[0.75fr_1.25fr] lg:px-8">
            <SectionHeading
              eyebrow="Frequently asked"
              title="The details behind the planning workflow."
              description="A short overview of what the current Invora product supports."
            />
            <div className="divide-y divide-border rounded-2xl border border-border bg-surface px-5 sm:px-6">
              {FAQS.map((faq) => (
                <details key={faq.question} className="group py-5">
                  <summary className="flex cursor-pointer list-none items-center justify-between gap-4 text-sm font-semibold text-foreground [&::-webkit-details-marker]:hidden">
                    {faq.question}
                    <span
                      aria-hidden="true"
                      className="text-lg text-primary transition-transform group-open:rotate-45"
                    >
                      +
                    </span>
                  </summary>
                  <p className="pr-8 pt-3 text-sm leading-6 text-foreground-muted">
                    {faq.answer}
                  </p>
                </details>
              ))}
            </div>
          </div>
        </section>

        <section className="px-4 pb-20 sm:px-6 sm:pb-28 lg:px-8">
          <div className="mx-auto max-w-7xl overflow-hidden rounded-3xl bg-primary px-6 py-12 text-primary-foreground shadow-xl sm:px-10 sm:py-16 lg:flex lg:items-end lg:justify-between lg:gap-10">
            <div className="max-w-2xl">
              <p className="text-sm font-semibold uppercase tracking-[0.14em] text-primary-foreground/75">
                Ready to plan with more context?
              </p>
              <h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">
                Turn inventory data into better decisions.
              </h2>
              <p className="mt-4 text-base leading-7 text-primary-foreground/80">
                Start with the connected workflows already available in Invora—then
                build a more deliberate replenishment rhythm.
              </p>
            </div>
            <div className="mt-8 flex flex-col gap-3 sm:flex-row lg:mt-0">
              <Link
                href={ROUTES.register}
                className="inline-flex h-11 items-center justify-center gap-2 rounded-md bg-surface px-5 text-sm font-semibold text-foreground transition-colors hover:bg-surface-muted"
              >
                Get started <Icon name="arrow-right" className="size-4" />
              </Link>
              <Link
                href={ROUTES.login}
                className="inline-flex h-11 items-center justify-center rounded-md border border-primary-foreground/30 px-5 text-sm font-semibold text-primary-foreground transition-colors hover:bg-primary-foreground/10"
              >
                Log in
              </Link>
            </div>
          </div>
        </section>
      </main>
      <footer className="border-t border-border bg-surface">
        <div className="mx-auto grid max-w-7xl gap-10 px-4 py-12 sm:grid-cols-2 sm:px-6 lg:grid-cols-[1.3fr_0.7fr_0.7fr_0.7fr] lg:px-8">
          <div>
            <InvoraMark />
            <p className="mt-4 max-w-sm text-sm leading-6 text-foreground-muted">
              Inventory intelligence for clearer demand planning, stock visibility,
              forecasting, and replenishment review.
            </p>
          </div>
          <FooterLinks
            title="Product"
            links={[
              { href: '#product', label: 'Product' },
              { href: '#how-it-works', label: 'How it works' },
              { href: '#capabilities', label: 'Capabilities' },
              { href: '#insights', label: 'Insights' },
            ]}
          />
          <FooterLinks
            title="Application"
            links={[
              { href: ROUTES.dashboard, label: 'Dashboard' },
              { href: ROUTES.products, label: 'Products' },
              { href: ROUTES.inventory, label: 'Inventory' },
              { href: ROUTES.forecastRuns, label: 'Forecasting' },
              { href: ROUTES.reports, label: 'Reports' },
            ]}
          />
          <FooterLinks
            title="Account"
            links={[
              { href: ROUTES.login, label: 'Log in' },
              { href: ROUTES.register, label: 'Register' },
              { href: '#faq', label: 'FAQ' },
            ]}
          />
        </div>
        <div className="border-t border-border">
          <div className="mx-auto max-w-7xl px-4 py-5 text-xs text-foreground-muted sm:px-6 lg:px-8">
            © {year} {APP_NAME}. All rights reserved.{' '}
            <span className="ml-2">{APP_TAGLINE}</span>
          </div>
        </div>
      </footer>
    </div>
  );
}
